[project]
name = "JPL"
version = "1.0.0"

# Optional, adding this will enable direct links from the documentation
# to your source code.
git_repo_url = "https://github.com/Gabriele-P03/JPL/"
git_default_branch = "main"

[paths]
output_dir = "docs"
compile_commands = "build/compile_commands.json"
